version: "3"
services:
    nodeexpress:
        image: fastapiimg
        ports:
                - 18080:18080
        build:
                context: .
                dockerfile: Dockerfile
        volumes:
                - /var/lib/jenkins/FONT:/AI/app/fontmaker/FONT
                - /home/ubuntu/test/download:/AI/app/fontmaker/download
                - /home/ubuntu/test/targetimg:/AI/app/fontmaker/targetimg
        container_name: fastapi-compose
        extra_hosts:
                - "host.docker.internal:host-gateway"


